name: Unit test

on: 
  push:
      branches: 
        ["master"]
    pull_request:
      branches: 
        ["master"]

jobs: 
   tests:
    runs-on: "ubuntu-latest"
    steps:
        - uses: actions/checkout@v3  
        - uses: use node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: '18.x' 
        - run: npm ci
        - run: npm test
        - name: Jest
