name: Unit test

on:
  
  push:
    branches: 
     - "**"
  pull_request:
    branches: ["master"]

jobs:
   
   tests:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2  
      - uses: "use node.js v18.15.0"
     uses: actions/setup-node@v1
        with:
          node-version: '18.x' 
      - run: npm ci
      - run: npm test
      - name: Jest
