name: CI(continuous integration)

on:
  push:
    branches:
      - main
      - test

jobs:

  pipeline-ci:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Setting Node.js
        uses: actions/setup-node@v2

      - name: Run tests
        run: npm install && npm run test 
      